### ISSUE TITLE
Only a quarter of available display size is used on Waveshare ESP32-S3 1.47 inch

### ISSUE THREAD

**Issue by kevinneuwirth** [i-am-shodan/USBArmyKnife#21]
Heya! With the Waveshare ESP32-S3 with the 1.47 inch screen, only the upper left quarter of the screen is used. I tried playing around with the display settings via Platformio but didnt really achieve anything apart from making it worse ...

**Comment by i-am-shodan** [comment]
What are you doing to fill the screen?

**Comment by kevinneuwirth** [comment]
Damn, you are absolutely right. I didn't think about the image's resolution at all! 

Sorry for wasting your time!

**Comment by i-am-shodan** [comment]
Not a problem, I'll add something to the Rick roll example
